version: '3'

services:
  redis:
    image: redis
    command: redis-server --requirepass redis2022!
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - thin-tmdb-network
    restart: always

  mysql:
    image: mysql:5.7
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mySql2022!"
      MYSQL_DATABASE: "thintmdb"
    ports:
      - "3306:3306"
    networks:
      - thin-tmdb-network
    restart: always

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - thin-tmdb-network

  lfr_tmdb:
    image: luisfelrib/lfr-tmdb
    ports:
      - "5000:5000"
    networks:
      - thin-tmdb-network
    restart: always
    depends_on:
        - mysql
        - redis

networks: 
  thin-tmdb-network:
    driver: bridge